### ISSUE TITLE
Bunny's QC report

### ISSUE THREAD

**Issue by Bunny5390** [butterfansubs/hataraku-saibou#1]
### Edit:

- [x] 00:01:18 Should this be "via blood circulation"?

![vlcsnap Cells at Work! - 11 5 - Heatstroke: What Would Happen With Pocari Sweat 00:01:18 745](https://user-images.githubusercontent.com/68522057/103269976-fa5f6a80-4984-11eb-9e08-effa0cd652ca.png)

### TS:

- [x] 00:02:15 The bottom left corner of the CNN sign overlaps the TV bezel ever so slightly, but I imagine fixing it isn't worth it.

- [x] Also, should the line break be before "by" instead of after? ~~I also kinda wonder if this should be via instead of by~~

![vlcsnap Cells at Work! - 11 5 - Heatstroke: What Would Happen With Pocari Sweat 00:02:15 719](https://user-images.githubusercontent.com/68522057/103270377-b751c700-4985-11eb-9ffc-8f62979e3bb1.png)

- [x] 00:03:49 I assume this sign isn't needed because it's the same as before?

![vlcsnap Cells at Work! - 11 5 - Heatstroke: What Would Happen With Pocari Sweat 00:03:49 354](https://user-images.githubusercontent.com/68522057/103270822-d56bf700-4986-11eb-90fa-45ecae9f3d33.png)

- [x] 00:06:26 Same here?

![vlcsnap Cells at Work! - 11 5 - Heatstroke: What Would Happen With Pocari Sweat 00:06:26 428](https://user-images.githubusercontent.com/68522057/103271218-9d18e880-4987-11eb-9d91-d0ab7187084b.png)

**Comment by petzku** [comment]
> 00:02:15 The bottom left corner of the CNN sign overlaps the TV bezel ever so slightly, but I imagine fixing it isn't worth it.

I'll see what I can do.

> Also, should the line break be before "by" instead of after? ~~I also kinda wonder if this should be via instead of by~~

Probably yes to both. Does this require reflecting in dialogue?

> 00:03:49 I assume this sign isn't needed because it's the same as before?
> 00:06:26 Same here?

Both were intentional, but could be done. Your call.

**Comment by Bunny5390** [comment]
> Probably yes to both. Does this require reflecting in dialogue?

Yeah it does. Can I leave that up to you when you edit the TS, or should I do it?

> Both were intentional, but could be done. Your call.

I think they're both fine, but should we put the CNN in the first one? Tbh I don't think it's worth it but I'll leave it up to you.

**Comment by petzku** [comment]
> I think they're both fine, but should we put the CNN in the first one? Tbh I don't think it's worth it but I'll leave it up to you.

Going to skip both of these, unless somebody has strong feelings about it. Marking them done for now.

**Comment by rcombs** [comment]
> Via blood circulation

"Through" means the same thing here, but yeah, "via" sounds better, so let's go with that.

**Comment by bucket3432** [comment]
All feedback addressed. Closing on @Bunny5390's behalf.
