### ISSUE TITLE
Typesetting QC report for 02 @ 9ef6502

### ISSUE THREAD

**Issue by bucket3432** [butterfansubs/hataraku-saibou#10]
Commit: 9ef6502

- [x] **0:11:47.98**: The outline should be slightly larger or darker.
  ![mpvshot Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  774CE03A 001152128](https://user-images.githubusercontent.com/22436557/108454442-4d0e2200-7264-11eb-8776-abd8f03e8b86.png)

- [x] **0:11:55.82**: Can we try to give this a little more depth so it looks more like a sign on the wall?
  ![mpvshot Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  774CE03A 001157508](https://user-images.githubusercontent.com/22436557/108454459-53040300-7264-11eb-9630-3a206c667785.png)

- [x] **0:16:05.49**: "MUR-MUR" stands out too much at the bottom. It either has not enough blur or the colour at the bottom of the gradient makes it stand out too much. If the latter, match the bottom colour with the colour of the text in the general area and create a gradient that would be a logical extension to the gradient of the original text.
  
  ![mpvshot Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  774CE03A 001606132](https://user-images.githubusercontent.com/22436557/108454502-6616d300-7264-11eb-8b9d-b2e733521e22.png)

- [x] **0:21:26.97**: I can see the edges of the mask. The text also seems to stand out, but I'm not sure if it's the tracking or that the text needs to be lighter.
  
  ![mpvshot Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  774CE03A 002127328](https://user-images.githubusercontent.com/22436557/108454521-70d16800-7264-11eb-990d-bbc7c6e29946.png)

**Comment by petzku** [comment]
>  0:21:26.97: [...] The text also seems to stand out, but I'm not sure if it's the tracking or that the text needs to be lighter.

There is something up with the tracking still, I'm not sure if there's anything I can do about it. Calling it "good enough" for now.
