### ISSUE TITLE
Bunny's editing QC report for 02 @ 59e12e7

### ISSUE THREAD

**Issue by Bunny5390** [butterfansubs/hataraku-saibou#11]
- [x] 02:17 - Should be "immune response **to** antibodies", not of.

![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  F78BA2EE  00:02:17 429](https://user-images.githubusercontent.com/68522057/108768080-3c400380-7525-11eb-835f-bc896567a234.png)

- [x] 02:32 - Something about the first line of the infobox here feels odd to me. "engulfing a cell to break down bacteria and foreign bodies" kinda makes it sound like the bacteria isn't the same thing as the cell being engulfed, and like the foreign bodies are necessarily cells ([Wikipedia says phagocytosis is just the engulfment of a large particle, not just a cell](https://en.wikipedia.org/wiki/Phagocytosis)).

![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  F78BA2EE  00:02:32 235](https://user-images.githubusercontent.com/68522057/108769380-e9ffe200-7526-11eb-899b-fcc5c3b234fb.png)

- [x] 02:38 - I assume it's like this either for characterization or line length reasons, but should this just be "Did I envision the end of the world?" or something similarly concise?

![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  F78BA2EE  00:02:38 158](https://user-images.githubusercontent.com/68522057/108769797-7b6f5400-7527-11eb-9f04-e28ae5a39efc.png)

- [x] 02:48 - Should there be a but at the start of the second half of the line? The two halves feel a little disjointed, I keep doing a double take every time I watch it to try to make sure I understood the line properly :thinking:.

![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  F78BA2EE  00:02:48 877](https://user-images.githubusercontent.com/68522057/108770463-4fa09e00-7528-11eb-97a0-d0ad15c543e2.png)
![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  F78BA2EE  00:02:52 756](https://user-images.githubusercontent.com/68522057/108770464-50393480-7528-11eb-875e-d067598f9de4.png)

- [x] 03:27 - Is this a typo? Should it be "antigens **or** foreign substances" or am I misunderstanding exactly what an antigen is? Is the antigen part of the foreign substance?

![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  F78BA2EE  00:03:27 916](https://user-images.githubusercontent.com/68522057/108770895-e3726a00-7528-11eb-9b38-1fa46adb7feb.png)

- [x] 06:11 - Can "useless" be used as an insult/derogatory name on its own? I've rarely seen it used as a noun and not as an adjective in part of a compound insult, eg "you useless (something)". Maybe "you useless leukocyte!"? Although I doubt the ordinary cells would know their technical name, they'd probably just call them white blood cells... :thinking:

![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  F78BA2EE  00:06:11 121](https://user-images.githubusercontent.com/68522057/108773819-e8d1b380-752c-11eb-8eb3-1b56140fb32d.png)

- [x] 06:55 - Didn't we decide we were going with "helper T cell commander" here?

![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  F78BA2EE  00:06:55 874](https://user-images.githubusercontent.com/68522057/108774633-e6238e00-752d-11eb-97a1-455c7fe72fa2.png)

- [x] 10:03 - Should this be viruses plural?

![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  F78BA2EE  00:10:03 228](https://user-images.githubusercontent.com/68522057/108775557-38b17a00-752f-11eb-8704-1212cc6a8c94.png)

- [x] 12:03 - Is there supposed to be a "the" before "three parts"?

![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  F78BA2EE  00:12:03 473](https://user-images.githubusercontent.com/68522057/108776134-f6d50380-752f-11eb-8f70-82eb403bc18a.png)

- [ ] 13:10: - Something about this line felt a bit off to me. What's he saying WBC is to blame for?

![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  F78BA2EE  00:13:10 540](https://user-images.githubusercontent.com/68522057/108776445-677c2000-7530-11eb-934c-afcad52f2517.png)

- [x] 13:47 - Nutrients is a bit of a weird word choice here, since nutrients are what are extracted from the food in the intestines and not what the bacteria would actually be on/in. TLC from Bucket: 

> the CCs have this:
> 栄養分の中で増殖した菌が攻めてきたんだ！
> which translates literally to "The germs that grew in the nutritious substance are attacking!" "Nutrients" is probably not the best word to use here.

![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  F78BA2EE  00:13:47 118](https://user-images.githubusercontent.com/68522057/108778978-36055380-7534-11eb-843b-c10fe7e83e11.png)

- [x] 13:55 - This seems to be plural bacteria so it should be "have landed", not has, right?

![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  F78BA2EE  00:13:55 376](https://user-images.githubusercontent.com/68522057/108777413-c4c4a100-7531-11eb-8ae6-47ee737eff8c.png)

- [x] 14:11 - Is this bacteria as in the plural of bacterium or bacteria as in the US English usage of a specific type of bacteria?

![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  F78BA2EE  00:14:11 476](https://user-images.githubusercontent.com/68522057/108777719-3f8dbc00-7532-11eb-986f-2bd747b28e73.png)

- [x] 14:26 - Missing an are/'re here after They

![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  F78BA2EE  00:14:26 741](https://user-images.githubusercontent.com/68522057/108779196-811f6680-7534-11eb-89c4-5aa3e158f774.png)

- [x] 15:52 and 15:55 - There's a bit of cognitive dissonance here because the VA says campylobacter twice when the word is onscreen once and only once when it's onscreen twice. Could these be redone slightly to fit the audio better?

![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  F78BA2EE  00:15:52 952](https://user-images.githubusercontent.com/68522057/108779669-381be200-7535-11eb-924d-11b00dc6ce6a.png)
![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  F78BA2EE  00:15:55 955](https://user-images.githubusercontent.com/68522057/108779670-381be200-7535-11eb-9bad-1ed682f19d4d.png)

**Comment by rcombs** [comment]
> Immune response to

Agreed.

> phagocytosis

"engulfing a bacterium, infected cell, or other object to break it down."

> End of the world

Nah I prefer this as-is; "envision the end of the world" reads less as prophecy and more as speculation imo

> …now I have[…]

Drop the … from the second line and cap the N.

> antigens

an antigen is the specific part of a foreign substance that produces an antibody response (e.g. in COVID-19, it's the Spike protein, or even specifically its RBD, rather than the entire virus)

> Can "useless" be used as an insult/derogatory name on its own?

yes, yes it can

> helper T

"helper T commander"

> Should this be viruses plural?

sure

> Is there supposed to be a "the" before "three parts"?

there should indeed not be

> to blame

Hmm, TLC? Maybe "You're the one at fault here."

> these nutrients

-> "this digestive fluid"?

> has landed

yup, should be "have"

> that bacteria

the mass-noun usage, but also, let's go with "those bacteria"

> Missing an are/'re

Go with "are"

> Of/by/for

Just join the events, it fits fine as a 2-liner.

**Comment by bucket3432** [comment]
>> to blame
>
> Hmm, TLC? Maybe "You're the one at fault here."

@rcombs The original is おめえが悪いんだぞ, which translates to "_You're_ the one in the wrong, you know." I think he's referring to how nonchalant and complacent WBC is, and is reminding WBC that his rebuttal holds less water because of it. In context, it could be that Killer T is saying that if WBC and his friends were massacred, it would be WBC's fault for being so laid back. "You're the one at fault here" I think captures all that.

**Comment by petzku** [comment]
Fixing infobox issues, would like confirmation on these:

> 02:17 - Should be "immune response to antibodies", not of.

"antibodies" or "antigens"?

> > phagocytosis
> 
> "engulfing a bacterium, infected cell, or other object to break it down."

How to split this line? I prefer the first option below. The second option is quite unbalanced, and the third has very bad semantic splitting.

<details>
<summary>Line split options that seemed reasonable</summary>

Before "or other", "englobement" on the same line:

![image](https://user-images.githubusercontent.com/5639335/109405100-884fd580-7975-11eb-8d11-fd259cd195b2.png)

"bacterium,\Ninfected cell", "englobement" on next line:

![image](https://user-images.githubusercontent.com/5639335/109405148-3a879d00-7976-11eb-9ad0-640fe932517e.png)

same as above, but move "Cells which" to the "englobement" line:

![image](https://user-images.githubusercontent.com/5639335/109405197-98b48000-7976-11eb-98f2-4b828ce3d8e3.png)

</details>

Leaving the other two commented in the file, ready to be applied with Cells Box.

**Comment by bucket3432** [comment]
@petzku 

> "antibodies" or "antigens"?

"antigens" is correct here.

> How to split this line?

I also prefer the first option.
