### ISSUE TITLE
Bunny's typesetting QC report for 02 @ 59e12e7

### ISSUE THREAD

**Issue by Bunny5390** [butterfansubs/hataraku-saibou#12]
- [x] 03:37 - Likely good enough:tm: but the lack of grainy texture on the Route does stand out a little, at least when I stop to look at the sign.

![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  F78BA2EE  00:03:37 759](https://user-images.githubusercontent.com/68522057/108771515-c8ecc080-7529-11eb-87fd-5955213338eb.png)

- [x] 06:29 - Still think it'd be fun to have the dialogue shake here along with the head bangs :D

![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  F78BA2EE  00:06:29 306](https://user-images.githubusercontent.com/68522057/108774400-9c3aa800-752d-11eb-9ac0-835daf7ddf69.png)

**Comment by petzku** [comment]
Route grain fixed, dialogue shenanigan awaiting consensus.

**Comment by bucket3432** [comment]
Dialogue shake has been added in 0d709c68a5b977b2393c491806095e0ea0f38642.
