### ISSUE TITLE
QC for 05daf87

### ISSUE THREAD

**Issue by bucket3432** [butterfansubs/hataraku-saibou#2]
Commit: 05daf87

## Editing

- [x] **0:05:29.53**: Are we keeping this "Onee-chan"? "Senpai" was translated earlier in the episode as "Big sis" (which I don't really like, but it was like that in episode 11).

  ![mpvshot cells_11 5_premux C0E584B4 000529538](https://user-images.githubusercontent.com/22436557/103426945-3711a880-4bb5-11eb-8afd-2e5f9ee41326.png)

- [x] **0:07:46.59**: The rest of the episode has cell names in lowercase.

  ![mpvshot cells_11 5_premux C0E584B4 000746633](https://user-images.githubusercontent.com/22436557/103427024-dc2c8100-4bb5-11eb-8464-824e6fcd6c61.png)

## Timing

- [x] **0:02:03.09**: This line starts two frames after the bubble appears. I would snap to the first frame with the bubble or reduce the lead-in time.

  ![mpvshot cells_11 5_premux C0E584B4 000203123](https://user-images.githubusercontent.com/22436557/103392823-86090080-4b17-11eb-8506-087b606c9242.png)

- [x] **0:04:19.95**: Extend end previous line to be continuous with this line.
- [x] **0:04:29.32**: Missing lead-in.
- [x] **0:04:33.72-0:05:06.00**: I would treat sign change boundaries like keyframes. Some of these lines start within two frames of a sign change.
- [x] **0:08:06.54**: Missing lead-in.
- [x] **0:09:44.49**: My gut says to extend this until just before the first frame where the circle appears (end at 0:09:46.39).

## Typesetting

- [x] **0:00:33.68**: I would either split the translated lines or move them above the original. It's a lot less busy up top. 

  ![mpvshot cells_11 5_premux C0E584B4 000034826](https://user-images.githubusercontent.com/22436557/103392618-bac88800-4b16-11eb-8c3d-0bceffb5fc1c.png)

- [x] **0:03:22.43**: The text could probably use a lower \\fscy to squish the vertical. It doesn't look squished enough compared to the original text, making the perspective look off.

  ![mpvshot cells_11 5_premux C0E584B4 000322452](https://user-images.githubusercontent.com/22436557/103393084-c7e67680-4b18-11eb-839e-128901622fad.png)

- [x] **0:04:10.56**: "Danger" needs more blur or a secondary border, something to dirty up the edges so it doesn't stand out as much.
  ![mpvshot cells_11 5_premux C0E584B4 000410584](https://user-images.githubusercontent.com/22436557/103393526-e2215400-4b1a-11eb-95f0-ded5acd95f27.png)

**Comment by rcombs** [comment]
> Are we keeping this "Onee-chan"?

Nooooope, I must've just missed that. I'd go for "big sis" again here; they're all one big happy family.

> White Blood Cell

Good catch, yup should be lowercase.

**Comment by bucket3432** [comment]
Suggested edits resolved in e4c2d537fdae3923e0166f02c632ca26877b64b8 and 3b3e36a8967d056826889aef9ab19ba6faaa5516.

**Comment by petzku** [comment]
>  0:04:10.56: "Danger" needs more blur or a secondary border, something to dirty up the edges so it doesn't stand out as much.

Should be done in 48a4911, and that should be everything.
![cells_11 5_premux C0E584B4 _001_6008](https://user-images.githubusercontent.com/5639335/103712798-66fce980-4fc3-11eb-9326-88df2a1bdad4.png)

**Comment by bucket3432** [comment]
I think that's everything. We should be good to go. Thanks!
