### ISSUE TITLE
Bunny's QC for 80fd543

### ISSUE THREAD

**Issue by Bunny5390** [butterfansubs/hataraku-saibou#5]
### Edit

- [x] 1:00, 1:04, 2:18 and 2:20: Should the first Wows and Gos here be capitalised when the rest of the romaji isn't anywhere? 
![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 01  4B54C2A1  00:02:18 055](https://user-images.githubusercontent.com/68522057/106348367-bf0dcf80-6293-11eb-8c49-d2c8aace7040.png)

- [x] 4:05: British spelling here, is that on purpose? 
![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 01  4B54C2A1  00:04:05 370](https://user-images.githubusercontent.com/68522057/106348603-6a6b5400-6295-11eb-941f-7dad92062116.png)

- [x] 4:27: I forget what we decided on this, is "foreign substances entering the body from outside" redundant?
![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 01  4B54C2A1  00:04:28 477](https://user-images.githubusercontent.com/68522057/106348664-cc2bbe00-6295-11eb-904d-79d273b3b4a2.png)

- [x] 8:12: I remember the second sentence here being discussed but I don't remember a verdict being reached. Don't the platelets adhere to each other as well as the vascular endothelial cells? Is the clumping together part enough?
![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 01  4B54C2A1  00:08:12 826](https://user-images.githubusercontent.com/68522057/106348843-5a547400-6297-11eb-9301-77e1ced046b6.png)

- [x] 9:39: Should there be an adverb of degree before incompetent here? eg. "because I'm so incompetent"
![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 01  4B54C2A1  00:09:39 871](https://user-images.githubusercontent.com/68522057/106349011-76a4e080-6298-11eb-8e2c-341cb694927a.png)

### Typesetting

- [x] 13:08 and 13:14: Colour slightly too light and blur too high?
![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 01  4B54C2A1  00:13:09 080](https://user-images.githubusercontent.com/68522057/106349373-7a863200-629b-11eb-9eb0-b4ffdace921d.png)

- [x] 20:13: Text and border colours seem a bit too light here for all four yays.
![vlcsnap  Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 01  4B54C2A1  00:20:13 129](https://user-images.githubusercontent.com/68522057/106349659-ac989380-629d-11eb-9553-7c4592c1eacb.png)

**Comment by rcombs** [comment]
TS:
- Should be "hemoglobin"
- Foreign/outside: it's technically redundant but sounds fairly natural, so I'm fairly ambivalent.
- Hemostasis: change "underneath" to "beneath"; otherwise I think this is fine.

**Comment by bucket3432** [comment]
Signing off and closing on behalf of @Bunny5390.
