### ISSUE TITLE
QC for 01 @ 80fd543

### ISSUE THREAD

**Issue by bucket3432** [butterfansubs/hataraku-saibou#6]
80fd543

## Editing

- [x] **0:00:22.68**: "All right" → "alright"
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L39
- [x] **0:04:31.58**: Later instances prefix the cell number with "No." It should probably be consistent throughout.
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L73
- [x] **0:04:54.14**: Break before "to".
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L80
- [x] **0:06:54.60**: "all right" → "alright"
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L111
- [x] **0:08:20.78**: "all right" → "alright"
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L142
- [x] **0:09:21.54**: Break before "the".
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L163
- [x] **0:09:33.97**: In the context of the next line, this reads as "But she yelled at me, but Master's absolutely right." Consider rewording.
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L166-L167
- [x] **0:09:44.23**: Break before "to" (or before "not").
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L169
- [x] **0:09:53.75**: Having "but" here sounds awkward, and 1146's speech isn't awkward.
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L171
- [x] **0:11:25.75**: "all right" → "alright"
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L198
- [x] **0:13:00.13**: "all right" → "alright"
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L231
- [x] **0:14:59.27**: Break after "unite".
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L274
- [x] **0:15:19.50**: Other info boxes and narration refer to the cell in the singular.
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L280
- [x] **0:15:37.80**: Break before "to".
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L288
- [x] **0:16:14.48**: Break before "the".
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L302
- [x] **0:17:35.16**: "all right" → "alright"
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L331
- [ ] **0:19:36.95**: I don't think the comma before "during" is necessary.
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L367
- [x] **0:19:46.42**: Break before "the".
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L369
- [x] **0:23:05.27**: "all right" → "alright"
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L401

## Styling

- [x] **0:07:05.78**: Set left margin to 1 to improve centering (0 causes ASS to use the margin defined in the style).
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L115

## Timing

- [x] **0:18:19.83**: This line should end before the keyframe where the white blood cells appear so it can't be confused as speech from them.
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L344
- [x] **0:19:14.76**: I would split this line after "efforts," and move the next clause to the following line.
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L359-L360
- [x] **0:19:22.71**: Needs more lead-in.
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Dialogue).ass#L362

## Typesetting

- [x] **0:03:45.25**: Missing dark border. It might also need less blur, but it's hard to tell without the border.
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Signs).ass#L79
  ![mpvshot Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 01  447F111D 000346685](https://user-images.githubusercontent.com/22436557/106375084-0aea7280-6381-11eb-91a6-4a03f987c2e8.png)
- [x] **0:05:45.66**: Missing fade. It should also be a bit closer to the original, where the space between the original and the TL is similar to the space between the two lines of the original. It would also jump out less if the foreground layer's blur were also 0.6 to match the border layer.
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Signs).ass#L344
  ![mpvshot Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 01  447F111D 000545720](https://user-images.githubusercontent.com/22436557/106375095-1d64ac00-6381-11eb-9f86-ca8903ac0960.png)
- [x] **0:09:27.59**: The character shakes of the TREMBLE signs could be a bit more pronounced.
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Signs).ass#L1164
- [x] **0:16:30.80**: The "WHOOSH" should take on a colour closer to the original text around that area so it doesn't look out of place, although it may help to gradient the text so it stands out just a little.
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Signs).ass#L5257
- [x] **0:20:09.15**: "CLATTER" should start sooner so it doesn't flash in.
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Signs).ass#L5521
- [x] **0:20:12.44**: The tracking of the "YAY"s on the right side could be tracked better.
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Signs).ass#L5618
- [x] **0:23:25.01**: This needs a thin dark border around the fill so it doesn't look lighter than the original.
  https://github.com/butterfansubs/hataraku-saibou/blob/80fd543b04a9d5167ca5cefefbac9a634636eef6/main/s2/01/Hataraku%20Saibou%202%20-%2001%20(Signs).ass#L81
  ![mpvshot Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 01  447F111D 002325154](https://user-images.githubusercontent.com/22436557/106375107-4127f200-6381-11eb-945c-1d9be63018ef.png)

**Comment by petzku** [comment]
All typesetting notes should now be addressed in [branch 01-bucket-QC-ts](/butterfansubs/hataraku-saibou/tree/01-bucket-QC-ts) (PR: #7).

**Comment by bucket3432** [comment]
I sign off on the timing and styling fixes.

**Comment by rcombs** [comment]
"Megakaryocytes": I'd prefer to use the plural on all of these; what are the other cases?

**Comment by bucket3432** [comment]
@rcombs I realized my note was ambiguous, but I was referring generally to info boxes that describe cells (with the exception of platelets) in this episode and in S1. The platelets are pluralized since they are presented as a group, but the rest are singular because only one of that cell is shown or focused on. If we were to follow the same logic, since only one megakaryocyte is shown, it should be singular. However, I don't think it would necessarily be wrong to pluralize all of them if you feel strongly about it as long as we're consistent.

**Comment by rcombs** [comment]
Yeah, I think using the plural for this sort of aside feels more natural in english.

**Comment by bucket3432** [comment]
With the note that "**0:19:36.95**: I don't think the comma before "during" is necessary." was intentionally left alone, this report is now fully resolved.
