### ISSUE TITLE
Editing/Styling QC report for 02 @ 9ef6502

### ISSUE THREAD

**Issue by bucket3432** [butterfansubs/hataraku-saibou#8]
Commit: 9ef6502

## Editing

- [x] **0:02:14.24**: Does "A type" agree with "Memory Cells"? The same feedback applies for all infoboxes with "a type" in their text.
  
  ![mpvshot Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  774CE03A 000216470](https://user-images.githubusercontent.com/22436557/108454360-1b955680-7264-11eb-8e08-297c7020a848.png)

- [x] **0:02:29.50**: "Phagocyte" should not be capitalized.
  https://github.com/butterfansubs/hataraku-saibou/blob/9ef6502bd19f413bf3c7685c1ba5102d62a0d833/main/s2/02/Hataraku%20Saibou%202%20-%2002%20(Dialogue).ass#L44
- [x] **0:02:48.18**: Break before "all".
  https://github.com/butterfansubs/hataraku-saibou/blob/9ef6502bd19f413bf3c7685c1ba5102d62a0d833/main/s2/02/Hataraku%20Saibou%202%20-%2002%20(Dialogue).ass#L51
- [x] **0:03:23.11**: "Immune Cells" should not be capitalized.
  https://github.com/butterfansubs/hataraku-saibou/blob/9ef6502bd19f413bf3c7685c1ba5102d62a0d833/main/s2/02/Hataraku%20Saibou%202%20-%2002%20(Dialogue).ass#L60
- [x] **0:03:27.19**: Remove "The" before "antibodies".
  
  ![mpvshot Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  774CE03A 000329292](https://user-images.githubusercontent.com/22436557/108454384-2cde6300-7264-11eb-8eca-e0f033d1844e.png)
- [x] **0:04:53.38**: Break after comma.
  https://github.com/butterfansubs/hataraku-saibou/blob/9ef6502bd19f413bf3c7685c1ba5102d62a0d833/main/s2/02/Hataraku%20Saibou%202%20-%2002%20(Dialogue).ass#L88
- [x] **0:06:52.93**: Should this be "to the commander, Helper T Cell" or "to Commander Helper T Cell"?
  https://github.com/butterfansubs/hataraku-saibou/blob/9ef6502bd19f413bf3c7685c1ba5102d62a0d833/main/s2/02/Hataraku%20Saibou%202%20-%2002%20(Dialogue).ass#L119
- [x] **0:07:14.08**: Break before second sentence.
  https://github.com/butterfansubs/hataraku-saibou/blob/9ef6502bd19f413bf3c7685c1ba5102d62a0d833/main/s2/02/Hataraku%20Saibou%202%20-%2002%20(Dialogue).ass#L126
- [x] **0:08:22.57**: Break before "and".
  https://github.com/butterfansubs/hataraku-saibou/blob/9ef6502bd19f413bf3c7685c1ba5102d62a0d833/main/s2/02/Hataraku%20Saibou%202%20-%2002%20(Dialogue).ass#L144
- [x] **0:08:27.36**: "all right" → "alright"
  https://github.com/butterfansubs/hataraku-saibou/blob/9ef6502bd19f413bf3c7685c1ba5102d62a0d833/main/s2/02/Hataraku%20Saibou%202%20-%2002%20(Dialogue).ass#L146
- [x] **0:12:47.37**: Break after "spot".
  https://github.com/butterfansubs/hataraku-saibou/blob/9ef6502bd19f413bf3c7685c1ba5102d62a0d833/main/s2/02/Hataraku%20Saibou%202%20-%2002%20(Dialogue).ass#L221
- [x] **0:13:50.77**: Episode 01 had a "No." prefix before cell numbers. Also break before "in".
  https://github.com/butterfansubs/hataraku-saibou/blob/9ef6502bd19f413bf3c7685c1ba5102d62a0d833/main/s2/02/Hataraku%20Saibou%202%20-%2002%20(Dialogue).ass#L240
- [x] **0:15:45.72**: Break before "commanding" if the balance is acceptable.
  https://github.com/butterfansubs/hataraku-saibou/blob/9ef6502bd19f413bf3c7685c1ba5102d62a0d833/main/s2/02/Hataraku%20Saibou%202%20-%2002%20(Dialogue).ass#L276
- [x] **0:16:02.38**: "All right" → "alright".
  https://github.com/butterfansubs/hataraku-saibou/blob/9ef6502bd19f413bf3c7685c1ba5102d62a0d833/main/s2/02/Hataraku%20Saibou%202%20-%2002%20(Dialogue).ass#L281
- [x] **0:16:15.19**: "All right" → "Alright"
  https://github.com/butterfansubs/hataraku-saibou/blob/9ef6502bd19f413bf3c7685c1ba5102d62a0d833/main/s2/02/Hataraku%20Saibou%202%20-%2002%20(Dialogue).ass#L286
- [x] **0:16:42.61**: "All right" → "Alright"
  https://github.com/butterfansubs/hataraku-saibou/blob/9ef6502bd19f413bf3c7685c1ba5102d62a0d833/main/s2/02/Hataraku%20Saibou%202%20-%2002%20(Dialogue).ass#L294
- [x] **0:17:58.99**: Break before "that".
  https://github.com/butterfansubs/hataraku-saibou/blob/9ef6502bd19f413bf3c7685c1ba5102d62a0d833/main/s2/02/Hataraku%20Saibou%202%20-%2002%20(Dialogue).ass#L318
- [x] **0:18:03.63**: Break before "an".
  https://github.com/butterfansubs/hataraku-saibou/blob/9ef6502bd19f413bf3c7685c1ba5102d62a0d833/main/s2/02/Hataraku%20Saibou%202%20-%2002%20(Dialogue).ass#L319

## Styling

- [x] **0:12:39.74**: Overlaps infobox.
  https://github.com/butterfansubs/hataraku-saibou/blob/9ef6502bd19f413bf3c7685c1ba5102d62a0d833/main/s2/02/Hataraku%20Saibou%202%20-%2002%20(Dialogue).ass#L219
  ![mpvshot Butter ᎓v  Hataraku Saibou!! (Cells at Work!!) - 02  774CE03A 001240927](https://user-images.githubusercontent.com/22436557/108454479-5d260180-7264-11eb-8cf1-44b3e3b48114.png)

**Comment by rcombs** [comment]
Applied everything except the TS changes. Agreed re: "The"; re: overlap, can the box be repositioned? I suppose the line could \an8 otherwise.

**Comment by petzku** [comment]
> re: overlap, can the box be repositioned? I suppose the line could \an8 otherwise.

The other options for the box positioning are not terribly good. Samples:

![infobox at top left](https://cdn.discordapp.com/attachments/770485705502752819/810940182081568928/unknown.png)

![infobox above dialogue, bottom right](https://cdn.discordapp.com/attachments/770485705502752819/810895760581066752/unknown.png)

The latter also looks quite awkward with one-liner dialogue lines.
